packages:
  - '.'
extra-deps:
  - git: https://github.com/poor-a/gssapi.git
    commit: 2e5e9c7be4ddef7d731fec200144ee39866ee209
  - heist-1.1.0.1
  - map-syntax-0.3
  - snap-1.1.2.0
  - git: https://github.com/poor-a/snaplet-fay.git
    commit: 7b19030edfe378e0577137a3a4af696d13b0615c
  - pwstore-fast-2.4.4
  - fay-jquery-0.6.1.0
  - fay-text-0.3.2.2
  - xmlhtml-0.2.5.2
  - pandoc-2.5
  - HsYAML-0.1.1.2
  - haddock-library-1.7.0
  - hslua-1.0.1
  - hslua-module-text-0.2.0
  - git: https://github.com/poor-a/digestive-functors.git
    commit: 847d45a2f7e56b79110ddaa3ec361dbc806fb28b
    subdirs:
        - digestive-functors
resolver: lts-12.25
