# A local, patched version of snaplet-fay-0.3.3.14 is needed.
# See ./docker/snaplet-fay-search-all-pkgdbs.patch
packages:
- '.'
extra-deps:
  - heist-1.0.1.1
  - map-syntax-0.2.0.2
  - snap-1.0.0.2
  - snaplet-fay-0.3.3.14
  - fay-base-0.20.0.1
  - fay-0.23.1.16
  - fay-jquery-0.6.1.0
  - fay-text-0.3.2.2
  - xmlhtml-0.2.5.2
  - spoon-0.3.1
  - type-eq-0.5
  - traverse-with-class-0.2.0.4
resolver: lts-9.14
