packages:
  - '.'
extra-deps:
  - git: https://github.com/poor-a/gssapi.git
    commit: 0ce712bf2e97e5ebdca5c2271bead31bb117e74c
  - heist-1.0.1.1
  - map-syntax-0.2.0.2
  - snap-1.0.0.2
  - git: https://github.com/poor-a/snaplet-fay.git
    commit: 8840019049211889a7984e63c4e5118cb51fcc4d
  - fay-base-0.20.0.1
  - fay-0.23.1.16
  - fay-jquery-0.6.1.0
  - fay-text-0.3.2.2
  - xmlhtml-0.2.5.2
  - spoon-0.3.1
  - type-eq-0.5
  - traverse-with-class-0.2.0.4
resolver: lts-9.21
