packages:
  - '.'
extra-deps:
  - git: https://github.com/poor-a/gssapi.git
    commit: 2e5e9c7be4ddef7d731fec200144ee39866ee209
  - heist-1.1.0.1
  - map-syntax-0.3
  - snap-1.1.2.0
  - pwstore-fast-2.4.4
  - xmlhtml-0.2.5.2
  - pandoc-2.5
  - HsYAML-0.1.1.2
  - haddock-library-1.7.0
  - hslua-1.0.1
  - hslua-module-text-0.2.0
  - esqueleto-2.6.0
resolver: lts-12.25
